"""USER REPOSITORY CONSTANTS"""
STATUS_FILTER = "IN_PROGRESS"
USER_TYPE = "CLIENT"
AVAILABLE_USER_QUERY_LABEL = "email_count"

"""HTTP STATUS CODES"""

HTTP_ERROR_CODE = 400
HTTP_NOT_FOUND_CODE = 404
HTTP_OK_CODE = 200


DATA_MESSAGE = "Data: "

""" Messages for User API """
USER_NOT_FOUND_ERROR = "User Not Found"
USER_FOUND_ALREADY = "Username Already Used"