"""USER REPOSITORY CONSTANTS"""
STATUS_FILTER = "IN_PROGRESS"
USER_TYPE = "CLIENT"
AVAILABLE_USER_QUERY_LABEL = "email_count"

"""HTTP STATUS CODES"""

HTTP_ERROR_CODE = 400
HTTP_NOT_FOUND_CODE = 404
HTTP_OK_CODE = 200
HTTP_BAD_REQUEST_CODE = 500

DATA_MESSAGE = "Data returned successfully"

""" Messages for User API """
STUDENT_NOT_FOUND_ERROR = "Student Not Found"
USER_FOUND_ALREADY = "Username Already Used"